export const Domains = {
    ACCOUNT: "/v1/accounts",
    AUTH: "/v1/auth",
    BLOG: "/v1/blogs",
    BOOKING: "/v1/bookings",
    CATEGORY: "/v1/categories",
    CHAT: "/v1/chats",
    CHAT_BOT: "/v1/chat-bot",
    COACH: "/v1/coaches",
    COMMENT: "/v1/comments",
    CONTACT: "/v1/contacts",
    COUNTER: "/v1/counters",
    FEEDBACK: "/v1/feedbacks",
    GOAL: "/v1/goals",
    HEALTH: "/v1/health",
    MEMBER: "/v1/members",
    MEMBERSHIP: "/v1/memberships",
    MESSAGE: "/v1/messages",
    NOTIFICATION: "/v1/notifications",
    PAYMENT: {
        STRIPE: "/v1/payment/payment/checkout",
    },
    PHASE: "/v1/phases",
    PLAN: "/v1/plans",
    RECORD: "/v1/records",
    REPORT: "/v1/reports",
    REVIEW: "/v1/reviews",
    SCORE: "/v1/scores",
    SETTING: "/v1/settings",
    STREAK: "/v1/streaks",
    SUBSCRIPTION: "/v1/subscriptions",
    TESTING: "/testing",
    TIMETABLE: "/v1/timetables",
    TRANSACTION: "/v1/transactions",
    UPLOAD_IMAGE: "/v1/upload/image",
    WEBHOOK: "/v1/webhooks",
}