export const testimonials = [
  {
    author: "data.testimonials.1.author",
    role: "data.testimonials.1.role",
    text: "data.testimonials.1.text",
    highlight: "data.testimonials.1.highlight",
    tags: ["data.testimonials.1.tags.0", "data.testimonials.1.tags.1"],
    rating: 5,
    date: "2024-02-15",
    verified: true,
    avatar: "/avatars/john.jpg",
  },
  {
    author: "data.testimonials.2.author",
    role: "data.testimonials.2.role",
    text: "data.testimonials.2.text",
    highlight: "data.testimonials.2.highlight",
    tags: ["data.testimonials.2.tags.0", "data.testimonials.2.tags.1"],
    rating: 5,
    date: "2024-03-01",
    verified: true,
    avatar: "/avatars/sarah.jpg",
  },
  {
    author: "data.testimonials.3.author",
    role: "data.testimonials.3.role",
    text: "data.testimonials.3.text",
    highlight: "data.testimonials.3.highlight",
    tags: ["data.testimonials.3.tags.0", "data.testimonials.3.tags.1"],
    rating: 4,
    date: "2024-02-28",
    verified: true,
    avatar: "/avatars/michael.jpg",
  },
];
