import type { HallOfFameMember, LeaderboardUser } from "@/types/leaderboard";

export const leaderboardData: LeaderboardUser[] = [
  {
    id: "1",
    name: "John Smith",
    rank: 1,
    score: 1500,
    smokeFreeDay: 365,
    badge: "Diamond",
    achievement: "1 Year Milestone",
    progress: 100,
    avatar: "/avatars/john.jpg",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    rank: 2,
    score: 1350,
    smokeFreeDay: 280,
    badge: "Platinum",
    achievement: "9 Month Strong",
    progress: 95,
    avatar: "/avatars/sarah.jpg",
  },
  {
    id: "3",
    name: "Michael Chen",
    rank: 3,
    score: 1200,
    smokeFreeDay: 200,
    badge: "Gold",
    achievement: "6 Month Warrior",
    progress: 90,
    avatar: "/avatars/michael.jpg",
  },
  {
    id: "4",
    name: "Emma Wilson",
    rank: 4,
    score: 1100,
    smokeFreeDay: 150,
    badge: "Silver",
    achievement: "5 Month Champion",
    progress: 85,
    avatar: "/avatars/emma.jpg",
  },
  {
    id: "5",
    name: "David Kim",
    rank: 5,
    score: 1000,
    smokeFreeDay: 120,
    badge: "Silver",
    achievement: "4 Month Victory",
    progress: 80,
  },
  {
    id: "6",
    name: "Maria Garcia",
    rank: 6,
    score: 950,
    smokeFreeDay: 90,
    badge: "Bronze",
    achievement: "3 Month Success",
    progress: 75,
    avatar: "/avatars/maria.jpg",
  },
  {
    id: "7",
    name: "Alex Thompson",
    rank: 7,
    score: 800,
    smokeFreeDay: 60,
    badge: "Bronze",
    achievement: "2 Month Progress",
    progress: 70,
  },
  {
    id: "8",
    name: "Lisa Brown",
    rank: 8,
    score: 700,
    smokeFreeDay: 45,
    badge: "Bronze",
    achievement: "45 Day Milestone",
    progress: 65,
    avatar: "/avatars/lisa.jpg",
  },
  {
    id: "9",
    name: "James Wilson",
    rank: 9,
    score: 600,
    smokeFreeDay: 30,
    badge: "Bronze",
    achievement: "1 Month Clean",
    progress: 60,
  },
  {
    id: "10",
    name: "Sophie Lee",
    rank: 10,
    score: 500,
    smokeFreeDay: 15,
    badge: "Bronze",
    achievement: "Getting Started",
    progress: 55,
    avatar: "/avatars/sophie.jpg",
  },
];

export const badges = {
  Diamond: { color: "text-blue-500", minDays: 365 },
  Platinum: { color: "text-slate-300", minDays: 180 },
  Gold: { color: "text-yellow-500", minDays: 90 },
  Silver: { color: "text-gray-400", minDays: 30 },
  Bronze: { color: "text-amber-600", minDays: 0 },
};

export const champions: HallOfFameMember[] = [
  {
    id: "1",
    name: "Michael Chen",
    achievement: "2 Years Smoke-Free Legend",
    date: "2023",
    avatar: "/avatars/michael.jpg",
    milestone: "Diamond Elite",
    daysSmokeFree: 730,
    moneySaved: "$5,840",
    story: "Started with small steps, now helping others in their journey."
  },
  {
    id: "2",
    name: "Sarah Williams",
    achievement: "18 Months Champion",
    date: "2023",
    avatar: "/avatars/sarah.jpg",
    milestone: "Diamond",
    daysSmokeFree: 547,
    moneySaved: "$4,376",
    story: "From pack-a-day to running marathons."
  },
  {
    id: "3",
    name: "James Rodriguez",
    achievement: "Community Leader Award",
    date: "2023",
    avatar: "/avatars/james.jpg",
    milestone: "Diamond",
    daysSmokeFree: 456,
    moneySaved: "$3,648",
    story: "Helped over 100 members in their quit journey."
  },
  {
    id: "4",
    name: "Emily Chang",
    achievement: "Most Inspiring Story",
    date: "2023",
    milestone: "Platinum",
    daysSmokeFree: 395,
    moneySaved: "$3,160",
    story: "Quit for my newborn daughter, never looked back."
  },
  {
    id: "5",
    name: "Robert Martinez",
    achievement: "Determination Award",
    date: "2023",
    avatar: "/avatars/robert.jpg",
    milestone: "Platinum",
    daysSmokeFree: 380,
    moneySaved: "$3,040",
    story: "Failed 5 times, succeeded on the 6th attempt."
  },
  {
    id: "6",
    name: "Lisa Anderson",
    achievement: "Health Transformation",
    date: "2023",
    avatar: "/avatars/lisa.jpg",
    milestone: "Platinum",
    daysSmokeFree: 365,
    moneySaved: "$2,920",
    story: "Lost 20 pounds and started teaching yoga."
  }
];
